### ISSUE TITLE
V-slot:tag remove function not working in 1.3.2?

### ISSUE THREAD

**Issue by vincerubinetti** [vueform/multiselect#36]
### Version

* Vue version: 3

### Demo

See the simple demo below. It is using [`1.3.0`](https://unpkg.com/@vueform/multiselect@1.3.0/dist/multiselect.global.js). Select a tag, then click it to remove it. It works. Now change the version to [`1.3.2`](https://unpkg.com/@vueform/multiselect@1.3.2/dist/multiselect.global.js). Select a tag, then click to remove it. An error is thrown and the tag isn't removed.

https://jsfiddle.net/do30skf2/1/

### Description

It seems like the `{ remove }` option is no longer present or working in `v-slot:tag`? In my actual project (setup using Vue CLI), I'm getting the error `runtime-core.esm-bundler.js?5c40:217 Uncaught TypeError: remove is not a function`.

**Comment by adamberecz** [comment]
It has changed to `handleTagRemove` in `1.3.2`. https://github.com/vueform/multiselect/blob/main/CHANGELOG.md#-bug-fixes

**Comment by vincerubinetti** [comment]
Thanks! I believe the readme has [a few places](https://github.com/vueform/multiselect#api) where that new prop name is not updated? I only see it in the example at the very end.
