### ISSUE TITLE
t.map is not a function - multiselect component unable to select from array of object options

### ISSUE THREAD

**Issue by mflan826** [vueform/multiselect#425]
### Version

* Vue version: 3

### Description

When :options is an array of objects containing label and value keys, when an option is selected, for following TypeError is thrown:

t.map is not a function
    at ej (vue.global.prod.js:5:10749)
    at vue.global.prod.js:5:10934
    at Array.map (<anonymous>)
    at Proxy.concat (vue.global.prod.js:5:10927)
    at Ce (multiselect.global.min.js:7:4878)
    at Pe (multiselect.global.min.js:7:6117)
    at Proxy.handleOptionClick (multiselect.global.min.js:7:9943)
    at onClick (multiselect.global.min.js:7:55535)
    at tZ (vue.global.prod.js:5:20832)
    at tY (vue.global.prod.js:5:20900)

### Demo

For reference, this issue also exists on Vueforms own demo current available here by attempting to select from example 3: https://jsfiddle.net/xajub20o/

**Comment by samueltomaselli** [comment]
Same problem here

**Comment by deepusv90** [comment]
Facing same problem here

**Comment by willbrowningme** [comment]
Same issue here, are you using Vite to compile?

**Comment by deepusv90** [comment]
Yes I am using Vite to compile. 

I'm not sure how, but it just started working again

**Comment by yusufkaracaburun** [comment]
Strange, I had the same problem, even after updating Vite to v5.4.2 it wasn't working. And now suddenly it started working again.

**Comment by darthf1** [comment]
Probably https://github.com/vuejs/core/issues/11792
